name: Create tar file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        ls -al

    - name: Create tar file
      run: |
        tar -cvf game_assets.tar index.html game.js dino.png obstacle.png star.png background.png
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: game_assets
        path: game_assets.tar
