name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
        # 如果需要构建步骤，请在这里添加
        # 例如：npm install && npm run build
        echo "Building project"

    - name: List files for debugging
      run: |
        ls -al

    - name: Create tar file
      run: |
        tar -cvf game_assets.tar index.html game.js dino.png obstacle.png star.png background.png

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./path_to_build_output  # 确保指定正确的输出目录
